# apiVersion: v1
# kind: Namespace
# metadata:
#   labels:
#     control-plane: redis-controller-manager
#   name: system
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: redis-controller-manager
spec:
  selector:
    matchLabels:
      control-plane: redis-controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: redis-controller-manager
        controller-component: redis-operator
    spec:
      containers:
      - command:
        - /manager
        env:
        - name: TZ
          value: Asia/Shanghai
        args:
        - --enable-leader-election
        image: controller:latest
        imagePullPolicy: Always
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 2048Mi
          requests:
            cpu: 100m
            memory: 2048Mi
      terminationGracePeriodSeconds: 10
      hostNetwork: true
      serviceAccount: redis-controller