# permissions for end users to view redis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redis-viewer-role
rules:
- apiGroups:
  - component.zhizuqiu
  resources:
  - redis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - component.zhizuqiu
  resources:
  - redis/status
  verbs:
  - get
